spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
  freemarker:
    cache: true
    charset: UTF-8
    suffix: .html
    content-type: text/html; charset=utf-8
  servlet:
    multipart:
      enabled: true
      file-size-threshold:
        0
      max-file-size:
        500MB
      max-request-size:
        500MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9999
  servlet:
    context-path: /QAQ
mybatis:
  type-aliases-package: com.ly.spring.entity
  mapper-locations:
  - classpath:mapper/*.xml
logging:
  level:
    com.ly.spring.dao: debug
